# Generated by Django 5.0.4 on 2024-04-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
