# Generated by Django 5.0.4 on 2024-06-23 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_alimento_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.alimento')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.alimento')),
            ],
        ),
    ]
